import {load,save} from './store.js';import {items} from './data.js';import {buildings,npcSeeds,phase,formatTime,npcLocation,buildingOpen,currentEvent,tick,locationName} from './engine.js';
let s=load(), selected=null;const $=q=>document.querySelector(q), el=(tag,c)=>{let e=document.createElement(tag);e.className=c;return e};
function addFeed(text){s.feed.unshift({text,time:formatTime(s.world.minutes)});s.feed=s.feed.slice(0,4)}
function toast(t){let x=$('#toast');x.textContent=t;x.classList.add('show');setTimeout(()=>x.classList.remove('show'),2400)}
function mod(html){$('#modalContent').innerHTML=html;$('#modal').classList.remove('hidden')}
function stat(n){return Math.round(s.player[n])}
function render(){let p=s.player,w=s.world,ph=phase(w.minutes),evt=currentEvent(s);$('#clock').textContent=formatTime(w.minutes);$('#date').textContent=`DAY ${String(w.day).padStart(2,'0')} · ${['MONDAY','TUESDAY','WEDNESDAY','THURSDAY','FRIDAY'][w.day%5]}`;$('#phase').textContent=ph.toUpperCase();$('#weatherIcon').textContent={Sunny:'☀',Cloudy:'☁',Rain:'☂',Storm:'ϟ',Fog:'≋'}[w.weather];$('#eventPill').textContent='✦ '+evt.name;$('#world').className='world '+ph+(w.weather==='Rain'?' rainy':'');$('#locationName').textContent=locationName(p.location);$('#profileName').textContent=s.user.name;$('#profileLevel').textContent=$('#levelNum').textContent=p.level;$('#xpText').textContent=`${p.xp} / ${p.level*125}`;$('#xpBar').style.width=(p.xp/(p.level*125)*100)+'%';['energy','hunger','mood','health'].forEach(k=>{$('#'+k+'Value').textContent=stat(k)+'%';$('#'+k+'Bar').style.width=stat(k)+'%'});$('#money').textContent=p.money.toLocaleString('id-ID');$('#invCount').textContent=Object.values(p.inventory).reduce((a,b)=>a+b,0);renderBuildings();renderNPCs();renderQuests();renderFeed();save(s)}
function renderBuildings(){let wrap=$('#buildings');wrap.innerHTML='';buildings.forEach(b=>{let x=el('div','building '+(!buildingOpen(b,s.world.minutes)?'closed':''));x.style.left=b.x+'%';x.style.top=b.y+'%';x.style.setProperty('--building',b.color);x.innerHTML=`<div class="roof"></div><div class="base"></div><div class="windows"></div><div class="sign">${b.name}</div>`;x.onclick=()=>openBuilding(b);wrap.append(x)})}
function renderNPCs(){let wrap=$('#npcs');wrap.innerHTML='';npcSeeds.forEach((n,i)=>{let loc=buildings.find(b=>b.id===npcLocation(n,s.world.minutes,s.world.weather,s.world.event));let x=el('div','character');x.style.left=(loc.x+12+(i%2)*5)+'%';x.style.top=(loc.y+56+(i%3)*3)+'%';x.innerHTML=`<div class="avatar" style="background:${n.color}">${n.name[0]}</div><span>${n.name.toUpperCase()}</span>`;x.onclick=()=>openNPC(n);wrap.append(x)})}
function renderQuests(){let a=s.quests.filter(q=>q.status==='Active');$('#questCount').textContent=a.length;$('#questList').innerHTML=a.map(q=>`<div class="quest"><div class="quest-top"><span>${q.title}</span><small>◈ ${q.reward}</small></div><p>${q.desc}</p><div class="quest-bar"><i style="width:${q.progress/q.target*100}%"></i></div></div>`).join('')||'<p>Semua quest selesai. Dunia menyiapkan sesuatu yang baru.</p>'}
function renderFeed(){$('#activityFeed').innerHTML=(s.feed.length?s.feed:[{text:'<b>Naya</b> sedang menjelajah Town Center.',time:'NOW'},{text:'<b>Neon Works</b> membuka shift pagi.',time:'06:00'}]).map(f=>`<div class="feed"><span>✦</span><span>${f.text}</span><time>${f.time}</time></div>`).join('')}
function complete(obj){let q=s.quests.find(q=>q.objective===obj&&q.status==='Active');if(q){q.progress=q.target;q.status='Completed';s.player.money+=q.reward;s.player.xp+=q.xp;addFeed(`<b>Quest complete:</b> ${q.title}`);toast(`QUEST COMPLETE +${q.reward} RC · +${q.xp} XP`);levelUp()}}
function levelUp(){let p=s.player;if(p.xp>=p.level*125){p.xp-=p.level*125;p.level++;toast('LEVEL UP! LEVEL '+p.level)}}
function openBuilding(b){selected=b.id;let open=buildingOpen(b,s.world.minutes);if(!open)return mod(`<h2>${b.name}</h2><p>Bangunan ini saat ini tutup. Jam buka: ${String(b.hours[0]).padStart(2,'0')}:00–${String(b.hours[1]).padStart(2,'0')}:00.</p>`);let content={market:`<p>Harga bergerak mengikuti denyut ekonomi Nexus. Festival memberi diskon 15%.</p>${shop(['sandwich','tea','notebook','jacket'])}`,restaurant:`<p>Istirahat sejenak dan pulihkan kebutuhanmu.</p>${shop(['sandwich','tea'])}`,home:`<p>Rumah pribadi Riki. Tempat paling aman untuk beristirahat dan menyimpan kenangan.</p><button class="action" data-act="rest">REST · +32 ENERGY</button><button class="action" data-act="decorate">AURORA DECOR · 190 RC</button>`,school:`<p>Ruang belajar adaptif. Pengetahuan tumbuh lewat praktik.</p><button class="action" data-act="study">STUDY PROGRAMMING · +10 XP</button><button class="action" data-act="social">SOCIAL WORKSHOP · +8 XP</button>`,work:`<p>Shift tersedia sampai pukul 18:00. Kerja keras tetap punya jeda.</p><button class="action" data-act="work">START SHIFT · +85 RC</button>`,park:`<p>Ruang hijau Luma. Udara di sini memperbaiki suasana hati.</p><button class="action" data-act="walk">TAKE A WALK · +14 MOOD</button>`,hospital:`<p>Care Nexus siap mendukung kesehatan warga.</p><button class="action" data-act="heal">HEALTH CHECK · +15 HEALTH</button>`,center:`<p>${currentEvent(s).desc}</p><button class="action" data-act="explore">EXPLORE DISTRICT · +5 XP</button>`}[b.type];mod(`<h2>${b.name}</h2>${content}`);complete('Visit Market');render();}
function shop(ids){return `<div>${ids.map(id=>{let it=items[id],price=Math.round(it.price*(s.world.event==='Festival'?.85:1));return `<div class="list-item"><div><b>${it.name}</b><small>${it.desc}</small></div><button class="action" data-buy="${id}">◈ ${price}</button></div>`}).join('')}</div>`}
function openNPC(n){selected='npc:'+n.id;let rel=s.relationships[n.id]||0;mod(`<h2>${n.name} <small>· ${n.job}</small></h2><p><b>${n.personality}</b> · Sedang berada di ${locationName(npcLocation(n,s.world.minutes,s.world.weather,s.world.event))}. Hubungan: ${rel<5?'Unknown':rel<15?'Acquaintance':'Friend'}.</p><button class="action" data-talk="${n.id}">TALK</button><button class="action" data-gift="${n.id}">GIVE SANDWICH</button>`)}
function action(act){let p=s.player;if(act==='rest'){p.energy=Math.min(100,p.energy+32);p.hunger=Math.max(10,p.hunger-5)}if(act==='study'){p.xp+=10;p.skills.Programming+=2}if(act==='social'){p.xp+=8;p.skills.Social+=2;p.mood=Math.min(100,p.mood+5)}if(act==='work'){p.money+=85;p.energy-=9;p.skills.Work+=2;complete('Work today')}if(act==='walk'){p.mood=Math.min(100,p.mood+14);p.energy-=2;complete('Visit Park')}if(act==='heal')p.health=Math.min(100,p.health+15);if(act==='explore'){p.xp+=5;p.mood=Math.min(100,p.mood+4)}addFeed(`<b>Riki</b> melakukan aktivitas di ${locationName(selected)}.`);levelUp();$('#modal').classList.add('hidden');render();toast('Aktivitas selesai')}
function inventory(){mod(`<h2>Inventory</h2><p>Barang yang kamu bawa dalam perjalanan hari ini.</p>${Object.entries(s.player.inventory).map(([id,n])=>`<div class="list-item"><div><b>${items[id].name} × ${n}</b><small>${items[id].cat} · ${items[id].desc}</small></div><button class="action" data-use="${id}">USE</button></div>`).join('')||'<p>Inventory masih kosong.</p>'}`)}
function skills(){mod(`<h2>Skills</h2>${Object.entries(s.player.skills).map(([n,v])=>`<div class="list-item"><b>${n}</b><small>LEVEL ${v} / 100</small></div>`).join('')}`)}
function social(){mod(`<h2>Nexus Community</h2>${npcSeeds.map(n=>`<div class="list-item"><b>${n.name} · ${n.job}</b><small>${s.relationships[n.id]<5?'Unknown':s.relationships[n.id]<15?'Acquaintance':'Friend'} · ${n.personality}</small></div>`).join('')}`)}
function profile(){mod(`<h2>Profile & Save</h2><p>Mock account tersimpan lokal secara aman di perangkat ini. Sistem ini dapat diganti dengan Firebase/Supabase tanpa mengubah world engine.</p><div class="list-item"><b>${s.user.name}</b><small>OFFLINE READY · AUTO-SAVED</small></div><button class="action" data-profile="rename">EDIT NAME</button><button class="action" data-profile="export">SAVE NOW</button><button class="action" data-profile="reset">RESET WORLD</button>`)}
function debug(cmd){let a=cmd.trim().split(/\s+/);if(a[0]==='/settime'){let [h,m]=a[1].split(':').map(Number);s.world.minutes=h*60+(m||0)}else if(a[0]==='/weather')s.world.weather=(a[1]||'Sunny')[0].toUpperCase()+(a[1]||'Sunny').slice(1);else if(a[0]==='/give'&&a[1]==='money')s.player.money+=Number(a[2])||0;else if(a[0]==='/event')s.world.event=a[1]==='festival'?'Festival':null;else if(a[0]==='/teleport'){let b=buildings.find(b=>b.id===a[1]);if(b)s.player.location=b.id}else {toast('Unknown command');return}toast('DEV: '+cmd);render()}
document.addEventListener('click',e=>{let b=e.target.closest('[data-buy]');if(b){let id=b.dataset.buy,price=Math.round(items[id].price*(s.world.event==='Festival'?.85:1));if(s.player.money<price)return toast('RIKI COIN tidak cukup');s.player.money-=price;s.player.inventory[id]=(s.player.inventory[id]||0)+1;addFeed(`<b>Purchased:</b> ${items[id].name}`);toast(`${items[id].name} added`);render();openBuilding(buildings.find(x=>x.id===selected));return}let u=e.target.closest('[data-use]');if(u){let id=u.dataset.use;s.player.inventory[id]--;if(!s.player.inventory[id])delete s.player.inventory[id];if(id==='sandwich')s.player.hunger=Math.min(100,s.player.hunger+24);if(id==='tea'){s.player.energy=Math.min(100,s.player.energy+12);s.player.mood=Math.min(100,s.player.mood+6)}toast(`${items[id].name} digunakan`);inventory();render();return}let t=e.target.closest('[data-talk]');if(t){let n=npcSeeds.find(x=>x.id===t.dataset.talk);s.relationships[n.id]+=5;s.player.mood=Math.min(100,s.player.mood+3);addFeed(`<b>${n.name}</b> menikmati percakapan dengan Riki.`);complete('Talk to Naya');toast(`Hubungan dengan ${n.name} +5`);$('#modal').classList.add('hidden');render();return}let g=e.target.closest('[data-gift]');if(g){if(!s.player.inventory.sandwich)return toast('Tidak ada Neon Sandwich');s.player.inventory.sandwich--;s.relationships[g.dataset.gift]+=8;toast('Hadiah diterima! Relationship +8');$('#modal').classList.add('hidden');render();return}let ac=e.target.closest('[data-act]');if(ac)action(ac.dataset.act);let pr=e.target.closest('[data-profile]');if(pr){if(pr.dataset.profile==='rename'){let n=prompt('Nama resident:',s.user.name);if(n)s.user.name=n.slice(0,18)}if(pr.dataset.profile==='export')toast('World state saved locally');if(pr.dataset.profile==='reset'&&confirm('Reset dunia?')){localStorage.removeItem('riki-digital-life-v1');location.reload()}render()}});
$('#closeModal').onclick=()=>$('#modal').classList.add('hidden');$('#modal').onclick=e=>{if(e.target===$('#modal'))$('#modal').classList.add('hidden')};$('#profileBtn').onclick=profile;$('#soundBtn').onclick=()=>toast('Audio ambience '+($('#soundBtn').textContent==='♪'?'ON':'OFF'))&&($('#soundBtn').textContent=$('#soundBtn').textContent==='♪'?'♪':'♪');$('#mapBtn').onclick=()=>mod(`<h2>Nexus District Map</h2><p>Gunakan bangunan di world view untuk berpindah. Area baru akan terbuka seiring level dan event komunitas.</p>${buildings.map(b=>`<div class="list-item"><b>${b.name}</b><button class="action" data-go="${b.id}">GO</button></div>`).join('')}`);document.addEventListener('click',e=>{let go=e.target.closest('[data-go]');if(go){s.player.location=go.dataset.go;addFeed(`<b>Riki</b> arrived at ${locationName(go.dataset.go)}.`);$('#modal').classList.add('hidden');render();toast('Lokasi diperbarui')}});$('#interactBtn').onclick=()=>{if(selected?.startsWith('npc:'))openNPC(npcSeeds.find(n=>'npc:'+n.id===selected));else openBuilding(buildings.find(b=>b.id===(selected||s.player.location))||buildings[7])};$('#actionBtn').onclick=()=>action('explore');$('#joystick').onclick=()=>{s.player.location='park';s.player.mood=Math.min(100,s.player.mood+2);render();toast('Riki berjalan ke Luma Park')};document.querySelectorAll('.dock button').forEach(b=>b.onclick=()=>{document.querySelectorAll('.dock button').forEach(x=>x.classList.remove('active'));b.classList.add('active');({inventory,social,skills,more:profile})[b.dataset.panel]?.()});
window.addEventListener('keydown',e=>{if(e.key==='i')inventory();if(e.key==='m')$('#mapBtn').click();if(e.key==='/' ){e.preventDefault();let c=prompt('Developer console · command');if(c)debug(c)}if(['ArrowUp','w','ArrowRight','d','ArrowDown','s','ArrowLeft','a'].includes(e.key)){let ids=['center','market','park','work'];s.player.location=ids[Math.floor(Math.random()*ids.length)];render()}});setInterval(()=>{tick(s);render()},5000);render();
